version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  server-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./server-app
    volumes:
      - /app/node_modules
      - ./server-app:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./client-app
    volumes:
      - /app/node_modules
      - ./client-app:/app
  worker-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker-app:/app
